# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

# Speed up build with travis caches
cache:
  directories:
    - $HOME/.gradle/wrapper/
    #TODO Sometimes Gradle caches cache-miss information in between builds.
    #We should reach out to gradle forum about this,
    #it might be a problem with how Gradle plugins work / Gradle plugin portal.
    #- $HOME/.gradle/caches/

language: java

jdk:
  - oraclejdk8

#don't build tags
branches:
  except:
  - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
 - true

script:
  - ./gradlew build -s && ./gradlew ciPerformRelease -s